/// One row per marketing campaign (200,000 rows, dated across 2021). Grain: Campaign ID. Holds spend, reach, engagement and return figures plus keys to each dimension.
table Campaigns
	lineageTag: 590e9401-79a4-4161-b218-058748ff8a9c

	/// Number of campaigns in the current filter context. Use this rather than counting Campaign ID.
	measure '# Campaigns' = COUNTROWS('Campaigns')
		formatString: #,##0
		displayFolder: Volume
		lineageTag: d194303f-edac-43f0-8c8f-c289527f4d87

	/// Total number of times campaign content was displayed.
	measure 'Total Impressions' = SUM('Campaigns'[Impressions])
		formatString: #,##0
		displayFolder: Volume
		lineageTag: e44c96f3-16cb-4c93-bfc3-1bb1d856a8da

	/// Total clicks generated by the campaigns.
	measure 'Total Clicks' = SUM('Campaigns'[Clicks])
		formatString: #,##0
		displayFolder: Volume
		lineageTag: be300f7f-6e7d-4c79-b81c-443ddefd117b

	/// Clicks divided by impressions. Weighted by impressions, so large campaigns count for more than in a simple average of campaign rates.
	measure 'Click-Through Rate' = DIVIDE([Total Clicks], [Total Impressions])
		formatString: 0.00%
		displayFolder: Engagement
		lineageTag: e7d3016f-1ba3-4419-8f94-c66dee9a3d02

	/// Mean engagement score across campaigns, on the source's 1 to 10 scale (10 = highest engagement).
	measure 'Average Engagement Score' = AVERAGE('Campaigns'[Engagement Score])
		formatString: 0.00
		displayFolder: Engagement
		lineageTag: 04b1d32f-a64d-4ab7-8075-95d2425d5a2e

	/// Total customer acquisition cost across campaigns.
	measure 'Total Acquisition Cost' = SUM('Campaigns'[Acquisition Cost])
		formatString: $#,##0
		displayFolder: Cost
		lineageTag: 8bc6fbca-c0e8-41a9-859a-4eed5250196d

	/// Mean acquisition cost per campaign.
	measure 'Average Acquisition Cost' = AVERAGE('Campaigns'[Acquisition Cost])
		formatString: $#,##0.00
		displayFolder: Cost
		lineageTag: 5dcf2eaf-355f-4bb5-bc17-7d514a528324

	/// Total acquisition cost divided by total clicks.
	measure 'Cost per Click' = DIVIDE([Total Acquisition Cost], [Total Clicks])
		formatString: $#,##0.00
		displayFolder: Cost
		lineageTag: 9bc79588-4a6d-44c6-b221-dcd82688aa15

	/// Simple mean of campaign conversion rates. Each campaign counts equally regardless of size; see Estimated Conversions for volume.
	measure 'Average Conversion Rate' = AVERAGE('Campaigns'[Conversion Rate])
		formatString: 0.00%
		displayFolder: Performance
		lineageTag: 0341e5ec-1e17-4856-848b-1f10827c90a9

	/// Clicks multiplied by conversion rate, summed per campaign. Assumes Conversion Rate is conversions per click; the source does not state its denominator.
	measure 'Estimated Conversions' = SUMX('Campaigns', 'Campaigns'[Clicks] * 'Campaigns'[Conversion Rate])
		formatString: #,##0
		displayFolder: Performance
		lineageTag: 1e0138fa-12f5-402c-8722-7e3217bda003

	/// Total acquisition cost divided by Estimated Conversions. Inherits the assumption behind Estimated Conversions.
	measure 'Cost per Estimated Conversion' = DIVIDE([Total Acquisition Cost], [Estimated Conversions])
		formatString: $#,##0.00
		displayFolder: Cost
		lineageTag: bd374e6b-2987-4585-a3dc-f1d7f14b4883

	/// Simple mean of campaign return on investment (ROI) values, as supplied in the source (a ratio, e.g. 5.0 = 5x). Each campaign counts equally; see Cost-Weighted ROI.
	measure 'Average ROI' = AVERAGE('Campaigns'[ROI])
		formatString: 0.00
		displayFolder: Performance
		lineageTag: 09e78df6-7805-4629-b012-b324ab2d5610

	/// Return on investment (ROI) weighted by acquisition cost, so higher-spend campaigns count for more. Prefer this over Average ROI when comparing groups of different spend.
	measure 'Cost-Weighted ROI' = DIVIDE(SUMX('Campaigns', 'Campaigns'[Acquisition Cost] * 'Campaigns'[ROI]), [Total Acquisition Cost])
		formatString: 0.00
		displayFolder: Performance
		lineageTag: 3cf5e916-0d39-4b4c-be92-ff988c4e7edd

	/// Average ROI as a percentage above or below the portfolio average. The portfolio is every campaign left after slicers and filters, ignoring the fields on the visual, so a channel or city is compared with the whole selection.
	measure 'ROI vs Portfolio (%)' =
			VAR _portfolio = CALCULATE([Average ROI], ALLSELECTED())
			RETURN DIVIDE([Average ROI] - _portfolio, _portfolio)
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Benchmark
		lineageTag: 18a3f385-6a21-479c-9343-a7dd2cb53961

	/// Click-through rate as a percentage above or below the portfolio rate. The portfolio is every campaign left after slicers and filters, ignoring the fields on the visual.
	measure 'Click-Through Rate vs Portfolio (%)' =
			VAR _portfolio = CALCULATE([Click-Through Rate], ALLSELECTED())
			RETURN DIVIDE([Click-Through Rate] - _portfolio, _portfolio)
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Benchmark
		lineageTag: df518a78-16e6-4cd8-bb10-d29677f90321

	/// Average conversion rate as a percentage above or below the portfolio average. The portfolio is every campaign left after slicers and filters, ignoring the fields on the visual.
	measure 'Conversion Rate vs Portfolio (%)' =
			VAR _portfolio = CALCULATE([Average Conversion Rate], ALLSELECTED())
			RETURN DIVIDE([Average Conversion Rate] - _portfolio, _portfolio)
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Benchmark
		lineageTag: 78aca512-d743-489e-bb46-611be5779ec6

	/// Average engagement score as a percentage above or below the portfolio average. The portfolio is every campaign left after slicers and filters, ignoring the fields on the visual.
	measure 'Engagement Score vs Portfolio (%)' =
			VAR _portfolio = CALCULATE([Average Engagement Score], ALLSELECTED())
			RETURN DIVIDE([Average Engagement Score] - _portfolio, _portfolio)
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Benchmark
		lineageTag: ebf1856d-069a-471a-afaf-676159f599b8

	/// Cost per click as a percentage above or below the portfolio cost per click. Unlike the other benchmark measures, a positive value is worse (more expensive).
	measure 'Cost per Click vs Portfolio (%)' =
			VAR _portfolio = CALCULATE([Cost per Click], ALLSELECTED())
			RETURN DIVIDE([Cost per Click] - _portfolio, _portfolio)
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Benchmark
		lineageTag: 846ac0ee-7372-4945-8601-09320367d053

	/// Unique identifier of the campaign. Use for drill-through to individual campaigns.
	column 'Campaign ID'
		dataType: int64
		formatString: 0
		lineageTag: a43024d6-6949-4d15-8396-bdf1ce96bc80
		summarizeBy: none
		sourceColumn: Campaign ID

	column 'Campaign Date'
		dataType: dateTime
		isHidden
		formatString: dd mmm yyyy
		isAvailableInMdx: false
		displayFolder: Keys
		lineageTag: 97744d66-ca8d-419f-a7a0-373e195f58df
		summarizeBy: none
		sourceColumn: Campaign Date

	/// Planned length of the campaign in days (15, 30, 45 or 60).
	column 'Duration Days'
		dataType: int64
		formatString: 0 "days"
		lineageTag: 73a73b4d-411f-4571-ad43-054a772ee226
		summarizeBy: none
		sourceColumn: Duration Days

	column 'Company Key'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		displayFolder: Keys
		lineageTag: ce89feb9-edf9-44c5-9644-7abb73cad468
		summarizeBy: none
		sourceColumn: Company Key

	column 'Campaign Type Key'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		displayFolder: Keys
		lineageTag: fef0ddeb-6641-4ac7-9ea9-9c9c311d8177
		summarizeBy: none
		sourceColumn: Campaign Type Key

	column 'Channel Key'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		displayFolder: Keys
		lineageTag: a98c4c52-d858-4de4-be79-52a00355d764
		summarizeBy: none
		sourceColumn: Channel Key

	column 'Target Audience Key'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		displayFolder: Keys
		lineageTag: 53108acd-ce8c-4509-814d-359cb73e7fd3
		summarizeBy: none
		sourceColumn: Target Audience Key

	column 'Customer Segment Key'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		displayFolder: Keys
		lineageTag: 94f3d4f9-5be0-4b41-9a4c-61d1f5abc78d
		summarizeBy: none
		sourceColumn: Customer Segment Key

	column 'Location Key'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		displayFolder: Keys
		lineageTag: 2887016b-2316-411d-a9a1-7883e4726d5a
		summarizeBy: none
		sourceColumn: Location Key

	column 'Language Key'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		displayFolder: Keys
		lineageTag: aecffe5c-eebf-4475-88d4-89043a8f2008
		summarizeBy: none
		sourceColumn: Language Key

	/// Conversion rate of the campaign as supplied in the source (0.04 = 4%). Aggregated by the measures in the Performance folder.
	column 'Conversion Rate'
		dataType: decimal
		isHidden
		formatString: 0.00%
		isAvailableInMdx: false
		displayFolder: Facts
		lineageTag: ba54ca69-5ae4-4798-9e68-467ae3fad44c
		summarizeBy: none
		sourceColumn: Conversion Rate

	/// Customer acquisition cost of the campaign in dollars. Aggregated by the measures in the Cost folder.
	column 'Acquisition Cost'
		dataType: decimal
		isHidden
		formatString: $#,##0.00
		isAvailableInMdx: false
		displayFolder: Facts
		lineageTag: 35a4d6e9-8b48-48ff-905e-2586e1924429
		summarizeBy: none
		sourceColumn: Acquisition Cost

	/// Return on investment (ROI) of the campaign as a ratio, as supplied in the source. Aggregated by the ROI measures.
	column ROI
		dataType: decimal
		isHidden
		formatString: 0.00
		isAvailableInMdx: false
		displayFolder: Facts
		lineageTag: dc279f9d-8f45-4feb-916a-8918f78c9e74
		summarizeBy: none
		sourceColumn: ROI

	/// Clicks the campaign generated.
	column Clicks
		dataType: int64
		isHidden
		formatString: #,##0
		isAvailableInMdx: false
		displayFolder: Facts
		lineageTag: 0b0d7609-04c3-48a3-b839-e206f963f43f
		summarizeBy: none
		sourceColumn: Clicks

	/// Times the campaign content was displayed.
	column Impressions
		dataType: int64
		isHidden
		formatString: #,##0
		isAvailableInMdx: false
		displayFolder: Facts
		lineageTag: bd4702b8-37c8-490a-9b2b-46052aba0a0b
		summarizeBy: none
		sourceColumn: Impressions

	/// Engagement score of the campaign on a 1 to 10 scale (10 = highest engagement).
	column 'Engagement Score'
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		displayFolder: Facts
		lineageTag: 74039f14-ebc4-4fc8-a0ba-846bded92558
		summarizeBy: none
		sourceColumn: Engagement Score

	partition Campaigns = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(#"Data Folder" & "marketing_campaign_dataset.csv"), [Delimiter = ",", Columns = 16, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Campaign_ID", Int64.Type}, {"Conversion_Rate", Currency.Type}, {"Acquisition_Cost", Currency.Type}, {"ROI", Currency.Type}, {"Clicks", Int64.Type}, {"Impressions", Int64.Type}, {"Engagement_Score", Int64.Type}}, "en-US"),
				    AddDate = Table.AddColumn(Typed, "Campaign Date", each Date.FromText([Date], [Format = "yyyy-MM-dd", Culture = "en-US"]), type date),
				    AddDuration = Table.AddColumn(AddDate, "Duration Days", each Number.FromText(Text.BeforeDelimiter([Duration], " ")), Int64.Type),
				    Companies = List.Buffer(List.Sort(List.Distinct(Promoted[Company]))),
				    CampaignTypes = List.Buffer(List.Sort(List.Distinct(Promoted[Campaign_Type]))),
				    Channels = List.Buffer(List.Sort(List.Distinct(Promoted[Channel_Used]))),
				    Audiences = List.Buffer(List.Sort(List.Distinct(Promoted[Target_Audience]))),
				    Segments = List.Buffer(List.Sort(List.Distinct(Promoted[Customer_Segment]))),
				    Locations = List.Buffer(List.Sort(List.Distinct(Promoted[Location]))),
				    Languages = List.Buffer(List.Sort(List.Distinct(Promoted[Language]))),
				    AddKeys = Table.AddColumn(AddDuration, "Keys", each [
				        #"Company Key" = List.PositionOf(Companies, [Company]) + 1,
				        #"Campaign Type Key" = List.PositionOf(CampaignTypes, [Campaign_Type]) + 1,
				        #"Channel Key" = List.PositionOf(Channels, [Channel_Used]) + 1,
				        #"Target Audience Key" = List.PositionOf(Audiences, [Target_Audience]) + 1,
				        #"Customer Segment Key" = List.PositionOf(Segments, [Customer_Segment]) + 1,
				        #"Location Key" = List.PositionOf(Locations, [Location]) + 1,
				        #"Language Key" = List.PositionOf(Languages, [Language]) + 1
				    ], type record),
				    ExpandKeys = Table.ExpandRecordColumn(AddKeys, "Keys", {"Company Key", "Campaign Type Key", "Channel Key", "Target Audience Key", "Customer Segment Key", "Location Key", "Language Key"}, {"Company Key", "Campaign Type Key", "Channel Key", "Target Audience Key", "Customer Segment Key", "Location Key", "Language Key"}),
				    KeyTypes = Table.TransformColumnTypes(ExpandKeys, {{"Company Key", Int64.Type}, {"Campaign Type Key", Int64.Type}, {"Channel Key", Int64.Type}, {"Target Audience Key", Int64.Type}, {"Customer Segment Key", Int64.Type}, {"Location Key", Int64.Type}, {"Language Key", Int64.Type}}),
				    Selected = Table.SelectColumns(KeyTypes, {"Campaign_ID", "Campaign Date", "Duration Days", "Company Key", "Campaign Type Key", "Channel Key", "Target Audience Key", "Customer Segment Key", "Location Key", "Language Key", "Conversion_Rate", "Acquisition_Cost", "ROI", "Clicks", "Impressions", "Engagement_Score"}),
				    Renamed = Table.RenameColumns(Selected, {{"Campaign_ID", "Campaign ID"}, {"Conversion_Rate", "Conversion Rate"}, {"Acquisition_Cost", "Acquisition Cost"}, {"Engagement_Score", "Engagement Score"}})
				in
				    Renamed

