/// Companies that ran the campaigns. One row per company.
table Company
	lineageTag: 9c43409b-db01-49ab-bff6-815518872866

	column 'Company Key'
		dataType: int64
		isHidden
		isKey
		formatString: 0
		isAvailableInMdx: false
		displayFolder: Keys
		lineageTag: dc44ca09-9a0b-4e6f-911b-a117b96a75c9
		summarizeBy: none
		sourceColumn: Company Key

	/// Name of the company that ran the campaign.
	column Company
		dataType: string
		lineageTag: 9070ad5d-78d1-41fc-b21b-f86c0adb15e1
		summarizeBy: none
		sourceColumn: Company

	partition Company = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(#"Data Folder" & "marketing_campaign_dataset.csv"), [Delimiter = ",", Columns = 16, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Members = List.Sort(List.Distinct(Promoted[Company])),
				    Dimension = Table.FromColumns({List.Numbers(1, List.Count(Members)), Members}, {"Company Key", "Company"}),
				    Typed = Table.TransformColumnTypes(Dimension, {{"Company Key", Int64.Type}, {"Company", type text}})
				in
				    Typed

